"""Add many_to_many, table borrowed_books

Revision ID: 48fe29d2833b
Revises: fff295cb7479
Create Date: 2025-06-03 20:12:34.558161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48fe29d2833b'
down_revision: Union[str, None] = 'fff295cb7479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowed_books',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reader_uuid', sa.Uuid(), nullable=False),
    sa.Column('book_uuid', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('borrow_date', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_uuid'], ['books.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reader_uuid'], ['readers.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrowed_books')
    # ### end Alembic commands ###
