"""Add many_to_many, table borrowed_books

Revision ID: dfa291ad790a
Revises: fff295cb7479
Create Date: 2025-06-02 22:52:11.538497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa291ad790a'
down_revision: Union[str, None] = 'fff295cb7479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowed_books',
    sa.Column('reader_uuid', sa.Uuid(), nullable=False),
    sa.Column('book_uuid', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_uuid'], ['books.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reader_uuid'], ['readers.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reader_uuid', 'book_uuid')
    )
    op.create_unique_constraint(None, 'readers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'readers', type_='unique')
    op.drop_table('borrowed_books')
    # ### end Alembic commands ###
